# Generated by Django 4.1.3 on 2022-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=120)),
                ('business_name', models.CharField(max_length=120)),
                ('stars', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonWordsAndPhrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=120)),
                ('phrase_type', models.TextField()),
                ('phrases', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=120)),
                ('stars', models.FloatField()),
                ('review_date', models.DateField()),
                ('review_text', models.TextField()),
            ],
        ),
    ]
